apiVersion: v1
kind: Pod
metadata:
  name: static-site
  labels:
    app: static-site
spec:
  containers:
    - name: static-site
      image: logesh2001/static-site:latest
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: caddy-config
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10